# Generated by Django 5.2.4 on 2025-08-04 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Local')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('esta_abierto', models.BooleanField(default=True, verbose_name='Está abierto')),
                ('horario_apertura', models.TimeField(verbose_name='Horario de Apertura')),
                ('horario_cierre', models.TimeField(verbose_name='Horario de Cierre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_locales/', verbose_name='Logo')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_imagenes/', verbose_name='Imagen del Producto')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='locales.local')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
