# Generated by Django 5.2.4 on 2025-08-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.RemoveField(
            model_name='local',
            name='esta_abierto',
        ),
        migrations.RemoveField(
            model_name='local',
            name='horario_apertura',
        ),
        migrations.RemoveField(
            model_name='local',
            name='horario_cierre',
        ),
        migrations.RemoveField(
            model_name='local',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
        migrations.AddField(
            model_name='local',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='locales/'),
        ),
        migrations.AlterField(
            model_name='local',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='local',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
